apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sniplink.fullname" . }}-config
  labels:
    {{- include "sniplink.labels" . | nindent 4 }}
data:
  PORT_SHORTENER: {{ .Values.shortener.service.port | quote }}
  PORT_ANALYTICS: {{ .Values.analytics.service.port | quote }}
  PGHOST: {{ include "sniplink.fullname" . }}-postgres
  PGPORT: {{ .Values.postgresql.service.port | quote }}
  PGDATABASE: {{ .Values.postgresql.auth.database | quote }}
  REDIS_HOST: {{ include "sniplink.fullname" . }}-redis
  REDIS_PORT: {{ .Values.redis.service.port | quote }}
  REDIS_URL: "redis://{{ include "sniplink.fullname" . }}-redis:{{ .Values.redis.service.port }}"
  RABBITMQ_HOST: {{ include "sniplink.fullname" . }}-rabbitmq
  RABBITMQ_PORT: {{ .Values.rabbitmq.service.amqpPort | quote }}
  BASE_URL: "http://localhost"
