global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'shortener'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['shortener:3001']
        labels:
          service: 'shortener'
          env: 'production'

  - job_name: 'analytics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['analytics:3002']
        labels:
          service: 'analytics'
          env: 'production'

  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          service: 'rabbitmq'
          env: 'production'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
